### ISSUE TITLE
failing to build

### ISSUE THREAD

**Issue by joeblew99** [visualfc/liteide#752]
i download the latest compiled version for OSX.

This is the nicest golang IDE i have used. Its really good.

But i cant get the build or govet to work from within the IDE.
go build -i [/Users/apple/workspace/go/src/github.com/ajstarks/svgo/svgplay]
Error: process failed to start.

**Comment by ckakman** [comment]
Make sure that the GOROOT variable is enabled and correct in the environment settings you use. "system" is the default one and there is an Edit button to the right of the environment selection combo box in the toolbox. There is also a "Edit current environment" menu item in the View menu.

**Comment by joeblew99** [comment]
thanks i got it working based on your help. cheers !!

**Comment by mauleyzaola** [comment]
I have been using LiteIDE in Linux for years without any trouble. In MacOS it wasn't working for me. So I am going to write what I did as a reminder to myself in the future and also, in case someone else struggles, might find this useful.

* From LiteIDE, select the right environment which should be `local` and 32/64 and OS selection. In my case is MAC OS 64, so I should pick `darwin64-local`

* Open a terminal and run this command

```
go env
```

Pay special attention to `GOROOT` value, since it may be different depending on which installation you executed (golang installer, brew, zip, etc). In my case I used brew, so the path value is
```
GOROOT="/usr/local/Cellar/go/1.8/libexec"
```
Lastly, copy/paste that value in LiteIDE environment. Save the file and you should be good to go.
