### ISSUE TITLE
PHP

### ISSUE THREAD

**Issue by cup** [visualfc/liteide#903]
Please add PHP language highlighting, thank you.

**Comment by Iqbal14** [comment]
Fenced code blocks do work in Markdown Gists, and in fact your code is being rendered that way. If you inspect the blocks you'll see that they are contained in divs with class="highlight highlight-PHP".

The problem is that PHP code is only recognized for highlighting by GFM if it includes the <?php delimiter. Add this to the top of each PHP block and you should be good to go, e.g.:

...

```php
<?php
class GO_Example_Model_Thing extends GO_Base_Db_ActiveRecord {
    ...

**Comment by svnpenn** [comment]
@Iqbal14 your comment has no bearing whatsoever on this issue

this issue is about syntax highlighting for **LiteIde**, not for GitHub or GFM
