### ISSUE TITLE
Option-3 should print hash.  Instead it toggles the build menu.

### ISSUE THREAD

**Issue by andy-js** [visualfc/liteide#960]
Please answer these questions before submitting your issue. Thanks!
Please download LiteIDE latest version and test before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?

X33.1
QT 5.6.2

### What version of Go are you using (`go version`)?

1.9.3

### What operating system and processor architecture are you using(`go env`)?

mac OS x86

### What did you do?

Attempted to type a hash (option-3) on my British keyboard but instead it triggers the "Build output" menu to toggle.

### What did you expect to see?

A hash sign.

### What did you see instead?

The "Build output" menu toggle.  It was like a giant middle finger.

**Comment by visualfc** [comment]
Option LiteApp "Use tool window shortcut" uncheck and restart LiteIDE.

**Comment by gonutz** [comment]
@andy-js please consider your choice of words here. "It was like a giant middle finger" is very inappropriate in the context of a github issue (except maybe if you were tricked into running a virus from a repo). It implies that the author of this software had bad intentions which is obviously not the case. The author provides a great IDE for free, this is a minor issue which is easily fixed with the right keyboard setting.

It is hard to consider all possible keyboard layouts when creating a program that is used all over the world, finding a default key mapping that fits everybody or creating an individual one for all countries is near impossible for a single developer. That would mean you had to first find out about all existing keyboard layouts, then test all of them every time you change something in the keyboard code. Put yourself in the author's shoes.

Please be more professional and show more respect in your comments, just as you would like people to talk to you.

**Comment by andy-js** [comment]
I was not implying the author of this software had anything other than good intentions, merely trying to best convey the sense of frustration that not having access to such a vital symbol causes.  I am well aware the software is free and grateful to have it.

@visualfc I could not find "Use tool window shortcut".  I have tried looking in Preferences->Lite Output->Keyboard but could not find any shortcuts that reference the Option key.

**Comment by visualfc** [comment]
![2018-07-22 5 06 52](https://user-images.githubusercontent.com/714279/43044079-00a14308-8dd2-11e8-8ace-d61afd401cc3.png)

**Comment by andy-js** [comment]
Thank you.
